package com.amcicustomer.enums;

public enum ConfigProperties {
    URL,
    BROWSER,
    PAGETITLE,
    VALIDEMAILID,
    VALIDPASSWORD,
    DASHBOARDURL,
    OVERRIDEREPORTS,
    PASSEDSTEPSCREENSHOTS,
    FAILEDSTEPSCREENSHOTS,
    SKIPEDSTEPSCREENSHOTS,
    RETRYFAILDTESTS,
    RUNMODE,
    ASSETNAME,



}
